name: Generate Icons Table

on:
  pull_request:
    branches:
      - main
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Markdown table for icons
        run: ./.github/readme-format.sh

      - name: Commit changes
        run: |
          git config --global user.name 'CI'
          git config --global user.email 'noreply@github.com'
          git add .
          git commit -m "Update"
          # Push back to the branch that triggered the PR
          git push origin HEAD:${GITHUB_REF#refs/heads/}